extends: default
ignore:
  - node_modules
  - vendor
CustomRules:
  DeprecatedFilter:
    enabled: true
    severity: warning

  AssetSizeCSS:
    enabled: true
    severity: suggestion
    threshold_in_bytes: 100_000

  BlockIdUsage:
    enabled: true
    severity: warning

  CSSBlockIdUsage:
    severity: warning
    message: "Avoid using {{ block.id }} directly in CSS for better maintainability."
    regex: '.*\|\s*({{.*block.id.*}}).*'  

  CSSThemeIdUsage:
    severity: warning
    message: "Avoid using Shopify section IDs (shopify-section-template-) in CSS."
    regex: '.*\|\s*(shopify-section-template-).*'  

  NoCustomCSS:
    severity: warning
    message: "A custom stylesheet 'custom.css' has been detected and should not be used."
    paths:
      - "!assets/custom.css"  # Warn if the file exists

  DeprecatedTag:
    enabled: true
    severity: warning

  ParserBlockingJavascript:
    enabled: true
    severity: error

  RemoteAsset:
    enabled: true
    severity: warning

  VariableName:
    enabled: true
    severity: warning
    format: snake_case