name: Code Quality Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Theme Check
        run: gem install theme-check

      - name: Run Theme Check
        run: theme-check .
