name: Code Quality Checks

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

      - name: Install Theme Check
        run: gem install theme-check

      - name: Run Theme Check
        run: theme-check .
