name: Code Quality Checks

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Theme Check
        run: gem install --user-install theme-check

      - name: Add Ruby Gems to PATH
        run: echo "$(ruby -r rubygems -e 'puts Gem.user_dir')/bin" >> $GITHUB_PATH

      - name: Run Theme Check with Custom Config
        run: theme-check -c theme-check.yml .
